FROM python:3.11-slim

# --- Java (requerido por Spark) ---
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-21-jre-headless \
    curl \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# --- Python dependencies ---
RUN pip install --no-cache-dir \
    pyspark==3.5.1 \
    boto3==1.34.0 \
    pandas==2.1.4 \
    pyarrow==14.0.2 \
    jupyter

# --- hadoop-aws jar (para leer S3 con s3a://) ---
RUN curl -o /usr/local/lib/python3.11/site-packages/pyspark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -o /usr/local/lib/python3.11/site-packages/pyspark/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# --- Directorio de trabajo ---
WORKDIR /app

# --- Variable de entorno para Spark ---
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3