services:
  etl:
    build: .
    container_name: airquality_etl
    volumes:
      - ./etl:/app/etl          # Código fuente (editable en vivo)
      - ./main.py:/app/main.py  # Entry point
      - ./data:/app/data        # Parquets persistidos en tu máquina
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: python main.py
